[package]
name = "dccon-dl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.28"
http = "0.2.9"
reqwest = "0.11.22"
tokio = { version = "1", features = ["full"] }
